# More-elaborate example compose file for CAS management image.
# In fact, not many parameters are mandatory - see README.md.
version: '3.2'

services:
  appserver:
    image: cas-management:latest
    container_name: cas-management
    ports:
      - 8009:8009
      - 8080:8080
    hostname: cas-management
    environment:
      - JAVA_XMS=768M
      - JAVA_XMX=1536M
      - TZ=Europe/Prague
      - DOCKER_TOMCAT_ENABLE_AJP=
#      - DOCKER_TOMCAT_DISABLE_ACCESS_LOG=
      - DOCKER_SECURE_SECRETS=yes
    volumes:
# This is for binding folder with PEM certificates to import into truststore.
      - type: bind
        source: ./certs
        target: /casmanagementstart/trustcert
        read_only: true
